issue-845-fix: true
resolve-type-alias: false
disable-version-string: true
with-expecter: true
packages:
  github.com/metaform/connector-fabric-manager/pmanager/api:
    interfaces:
      Orchestrator:
        config:
          filename: orchestrator_mock.go
          outpkg: mocks
          dir: ./api/mocks
      ProvisionManager:
        config:
          filename: provision_mock.go
          outpkg: mocks
          dir: ./api/mocks
      DefinitionManager:
        config:
          filename: definition_manager_mock.go
          outpkg: mocks
          dir: ./api/mocks
