// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	jetstream "github.com/nats-io/nats.go/jetstream"
	mock "github.com/stretchr/testify/mock"

	nats "github.com/nats-io/nats.go"
)

// MockMsgClient is an autogenerated mock type for the MsgClient type
type MockMsgClient struct {
	mock.Mock
}

type MockMsgClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMsgClient) EXPECT() *MockMsgClient_Expecter {
	return &MockMsgClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, key
func (_m *MockMsgClient) Get(ctx context.Context, key string) (jetstream.KeyValueEntry, error) {
	ret := _m.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 jetstream.KeyValueEntry
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (jetstream.KeyValueEntry, error)); ok {
		return rf(ctx, key)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) jetstream.KeyValueEntry); ok {
		r0 = rf(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jetstream.KeyValueEntry)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMsgClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMsgClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockMsgClient_Expecter) Get(ctx interface{}, key interface{}) *MockMsgClient_Get_Call {
	return &MockMsgClient_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockMsgClient_Get_Call) Run(run func(ctx context.Context, key string)) *MockMsgClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMsgClient_Get_Call) Return(_a0 jetstream.KeyValueEntry, _a1 error) *MockMsgClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMsgClient_Get_Call) RunAndReturn(run func(context.Context, string) (jetstream.KeyValueEntry, error)) *MockMsgClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: ctx, subject, payload, opts
func (_m *MockMsgClient) Publish(ctx context.Context, subject string, payload []byte, opts ...jetstream.PublishOpt) (*jetstream.PubAck, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, subject, payload)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 *jetstream.PubAck
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, ...jetstream.PublishOpt) (*jetstream.PubAck, error)); ok {
		return rf(ctx, subject, payload, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, ...jetstream.PublishOpt) *jetstream.PubAck); ok {
		r0 = rf(ctx, subject, payload, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jetstream.PubAck)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte, ...jetstream.PublishOpt) error); ok {
		r1 = rf(ctx, subject, payload, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMsgClient_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockMsgClient_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - subject string
//   - payload []byte
//   - opts ...jetstream.PublishOpt
func (_e *MockMsgClient_Expecter) Publish(ctx interface{}, subject interface{}, payload interface{}, opts ...interface{}) *MockMsgClient_Publish_Call {
	return &MockMsgClient_Publish_Call{Call: _e.mock.On("Publish",
		append([]interface{}{ctx, subject, payload}, opts...)...)}
}

func (_c *MockMsgClient_Publish_Call) Run(run func(ctx context.Context, subject string, payload []byte, opts ...jetstream.PublishOpt)) *MockMsgClient_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]jetstream.PublishOpt, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(jetstream.PublishOpt)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), variadicArgs...)
	})
	return _c
}

func (_c *MockMsgClient_Publish_Call) Return(_a0 *jetstream.PubAck, _a1 error) *MockMsgClient_Publish_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMsgClient_Publish_Call) RunAndReturn(run func(context.Context, string, []byte, ...jetstream.PublishOpt) (*jetstream.PubAck, error)) *MockMsgClient_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// PublishMsg provides a mock function with given fields: ctx, msg, opts
func (_m *MockMsgClient) PublishMsg(ctx context.Context, msg *nats.Msg, opts ...jetstream.PublishOpt) (*jetstream.PubAck, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, msg)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PublishMsg")
	}

	var r0 *jetstream.PubAck
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *nats.Msg, ...jetstream.PublishOpt) (*jetstream.PubAck, error)); ok {
		return rf(ctx, msg, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *nats.Msg, ...jetstream.PublishOpt) *jetstream.PubAck); ok {
		r0 = rf(ctx, msg, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*jetstream.PubAck)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *nats.Msg, ...jetstream.PublishOpt) error); ok {
		r1 = rf(ctx, msg, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMsgClient_PublishMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishMsg'
type MockMsgClient_PublishMsg_Call struct {
	*mock.Call
}

// PublishMsg is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *nats.Msg
//   - opts ...jetstream.PublishOpt
func (_e *MockMsgClient_Expecter) PublishMsg(ctx interface{}, msg interface{}, opts ...interface{}) *MockMsgClient_PublishMsg_Call {
	return &MockMsgClient_PublishMsg_Call{Call: _e.mock.On("PublishMsg",
		append([]interface{}{ctx, msg}, opts...)...)}
}

func (_c *MockMsgClient_PublishMsg_Call) Run(run func(ctx context.Context, msg *nats.Msg, opts ...jetstream.PublishOpt)) *MockMsgClient_PublishMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]jetstream.PublishOpt, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(jetstream.PublishOpt)
			}
		}
		run(args[0].(context.Context), args[1].(*nats.Msg), variadicArgs...)
	})
	return _c
}

func (_c *MockMsgClient_PublishMsg_Call) Return(_a0 *jetstream.PubAck, _a1 error) *MockMsgClient_PublishMsg_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMsgClient_PublishMsg_Call) RunAndReturn(run func(context.Context, *nats.Msg, ...jetstream.PublishOpt) (*jetstream.PubAck, error)) *MockMsgClient_PublishMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Stream provides a mock function with given fields: ctx, streamName
func (_m *MockMsgClient) Stream(ctx context.Context, streamName string) (jetstream.Stream, error) {
	ret := _m.Called(ctx, streamName)

	if len(ret) == 0 {
		panic("no return value specified for Stream")
	}

	var r0 jetstream.Stream
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (jetstream.Stream, error)); ok {
		return rf(ctx, streamName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) jetstream.Stream); ok {
		r0 = rf(ctx, streamName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(jetstream.Stream)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, streamName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMsgClient_Stream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stream'
type MockMsgClient_Stream_Call struct {
	*mock.Call
}

// Stream is a helper method to define mock.On call
//   - ctx context.Context
//   - streamName string
func (_e *MockMsgClient_Expecter) Stream(ctx interface{}, streamName interface{}) *MockMsgClient_Stream_Call {
	return &MockMsgClient_Stream_Call{Call: _e.mock.On("Stream", ctx, streamName)}
}

func (_c *MockMsgClient_Stream_Call) Run(run func(ctx context.Context, streamName string)) *MockMsgClient_Stream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMsgClient_Stream_Call) Return(_a0 jetstream.Stream, _a1 error) *MockMsgClient_Stream_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMsgClient_Stream_Call) RunAndReturn(run func(context.Context, string) (jetstream.Stream, error)) *MockMsgClient_Stream_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, key, value, version
func (_m *MockMsgClient) Update(ctx context.Context, key string, value []byte, version uint64) (uint64, error) {
	ret := _m.Called(ctx, key, value, version)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, uint64) (uint64, error)); ok {
		return rf(ctx, key, value, version)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, uint64) uint64); ok {
		r0 = rf(ctx, key, value, version)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte, uint64) error); ok {
		r1 = rf(ctx, key, value, version)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMsgClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMsgClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - value []byte
//   - version uint64
func (_e *MockMsgClient_Expecter) Update(ctx interface{}, key interface{}, value interface{}, version interface{}) *MockMsgClient_Update_Call {
	return &MockMsgClient_Update_Call{Call: _e.mock.On("Update", ctx, key, value, version)}
}

func (_c *MockMsgClient_Update_Call) Run(run func(ctx context.Context, key string, value []byte, version uint64)) *MockMsgClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte), args[3].(uint64))
	})
	return _c
}

func (_c *MockMsgClient_Update_Call) Return(_a0 uint64, _a1 error) *MockMsgClient_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMsgClient_Update_Call) RunAndReturn(run func(context.Context, string, []byte, uint64) (uint64, error)) *MockMsgClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMsgClient creates a new instance of MockMsgClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMsgClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMsgClient {
	mock := &MockMsgClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
